# C-PAC Testing Data Configuration File
# v1.6.2
# 
# this is a cross-section of multiple datasets meant for the C-PAC release regression test

- anat: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/ADHD200/RawDataBIDS/KKI/sub-1019436/ses-1/anat/sub-1019436_ses-1_run-1_T1w.nii.gz
  func:
    rest_acq-1_run-1:
      scan: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/ADHD200/RawDataBIDS/KKI/sub-1019436/ses-1/func/sub-1019436_ses-1_task-rest_acq-1_run-1_bold.nii.gz
      scan_parameters: /ocean/projects/med220004p/shared/data_raw/CPAC-Regression/ADHD200/RawDataBIDS/KKI/task-rest_acq-1_bold.json
  site_id: KKI
  subject_id: '1019436'
  unique_id: '1'